        <?php
        $strength = WoW_Characters::GetCharacterStrength();
        $agility = WoW_Characters::GetCharacterAgility();
        $stamina = WoW_Characters::GetCharacterStamina();
        $intellect = WoW_Characters::GetCharacterIntellect();
        $spirit = WoW_Characters::GetCharacterSpirit();
        $melee_stats = WoW_Characters::GetMeleeStats();
        $ranged_stats = WoW_Characters::GetRangedStats();
        $spell = WoW_Characters::GetSpellStats();
        $defense = WoW_Characters::GetDefenseStats();
        $resistances = WoW_Characters::GetResistanceStats();
        ?>
        <script type="text/javascript">
	//<![CDATA[
		$(document).ready(function() {
			new Summary.Stats({

			"health": <?php echo WoW_Characters::GetHealth(); ?>,
			"power": <?php echo WoW_Characters::GetPowerValue(); ?>,
			"powerTypeId": <?php echo WoW_Characters::GetPowerType(); ?>,
			"hasOffhandWeapon": false,
			"masteryName": "",
			"masteryDescription": "",
			"averageItemLevelEquipped": <?php echo WoW_Characters::GetAVGEquippedItemLevel(); ?>,
			"averageItemLevelBest": <?php echo WoW_Characters::GetAVGItemLevel(); ?>,
			"dmgMainMax": <?php echo $melee_stats['damage']['max']; ?>,
			"dmgMainMin": <?php echo $melee_stats['damage']['min']; ?>,
			"resilience_crit": -1,
			"holyResist": 0,
			"spellHitRating": <?php echo $spell['hit_rating']['value']; ?>,
			"agiBase": <?php echo $agility['base']; ?>,
			"rangeAtkPowerBase": <?php echo $ranged_stats['attack_power']['effective']; ?>,
			"expertiseOffPercent": <?php echo $melee_stats['expertise_rating']['percent']; ?>,
			"critPercent": <?php echo $melee_stats['crit_rating']['percent']; ?>,
			"dmgOffMin": 0,
			"spellDmg_petAp": -1,
			"agi_armor": <?php echo $agility['armor']; ?>,
			"rangeCritPercent": <?php echo $melee_stats['crit_rating']['percent']; // they are the same. ?>,
			"resistHoly_pet": -1,
			"dodgeRatingPercent": <?php echo $defense['dodge']['increasePercent']; ?>,
			"parryRating": <?php echo $defense['parry']['rating']; ?>,
			"parry": <?php echo $defense['parry']['percent']; ?>,
			"rangeBonusWeaponRating": 0,
			"atkPowerBase": <?php echo $melee_stats['attack_power']['base']; ?>,
			"str_ap": <?php echo $strength['attack']; ?>,
			"hitRating": <?php echo $melee_stats['hit_rating']['value']; ?>,
			"block_damage": <?php echo $defense['block']['percent']; ?>,
			"dmgOffMax": 0,
			"masteryRating": 0,
			"spellCritRating": <?php echo $spell['crit_rating']['rating']; ?>,
			"bonusOffWeaponRating": 0,
			"resilience_damage": <?php echo $defense['resilience']['damagePercent']; ?>,
			"resilience": <?php echo $defense['resilience']['value']; ?>,
			"masteryRatingBonus": 0,
			"expertiseOff": 0,
			"dmgMainSpeed": <?php echo $melee_stats['damage']['haste']; ?>,
			"rangeAtkPowerBonus": 0,
			"expertiseMain": 0,
			"shadowDamage": <?php echo $spell['power']['value']; ?>,
			"defensePercent": 0,
			"rangeHitRating": <?php echo $melee_stats['hit_rating']['value']; ?>,
			"blockRating": <?php echo $defense['block']['rating']; ?>,
			"spellDmg_petSpellDmg": -1,
			"shadowResist": <?php echo $resistances['resistance']['shadow']; ?>,
			"armor_petArmor": -1,
			"block": <?php echo $defense['block']['percent']; ?>,
			"dmgOffDps": 0,
			"resistNature_pet": -1,
			"dmgRangeMax": <?php echo $ranged_stats['damage']['max']; ?>,
			"armorPercent": <?php echo $defense['armor']['reductionPercent']; ?>,
			"resistArcane_pet": -1,
			"dmgMainDps": <?php echo $melee_stats['damage']['dps']; ?>,
			"spellHitRatingPercent": <?php echo $spell['hit_rating']['increasedHitPercent']; ?>,
			"healing": <?php echo $spell['power']['value']; ?>,
			"manaRegenPerFive": <?php echo $spell['mana_regen']['notCasting']; ?>,
			"str_block": <?php echo $strength['block']; ?>,
			"rangeAtkPowerLoss": 0,
			"dmgRangeDps": <?php echo $ranged_stats['damage']['dps']; ?>,
			"frostCrit": <?php echo $spell['crit_rating']['rating']; ?>,
			"armorPenetrationPercent": 0,
			"rangeCritRating": <?php echo $melee_stats['crit_rating']['value']; ?>,
			"fireDamage": <?php echo $spell['power']['value']; ?>,
			"resistShadow_pet": -1,
			"shadowCrit": <?php echo $spell['crit_rating']['rating']; ?>,
			"hasteRating": <?php echo $melee_stats['haste_rating']['hasteRating']; ?>,
			"rangeHitRatingPercent": <?php echo $melee_stats['hit_rating']['increasedHitPercent']; // they are the same ?>,
			"natureResist": <?php echo $resistances['resistance']['nature']; ?>,
			"arcaneDamage": <?php echo $spell['power']['value']; ?>,
			"intTotal": <?php echo $intellect['effective']; ?>,
			"expertiseRating": 0,
			"bonusOffMainWeaponSkill": 0,
			"expertiseMainPercent": <?php echo $melee_stats['expertise_rating']['percent']; ?>,
			"agiTotal": <?php echo $agility['effective']; ?>,
			"frostResist": <?php echo $resistances['resistance']['frost']; ?>,
			"int_mp": <?php echo $intellect['mana']; ?>,
			"arcaneCrit": <?php echo $spell['crit_rating']['rating']; ?>,
			"ap_dps": <?php echo $melee_stats['attack_power']['increasedDps']; ?>,
			"holyCrit": <?php echo $spell['crit_rating']['rating']; ?>,
			"atkPowerLoss": 0,
			"staBase": <?php echo $stamina['base']; ?>,
			"bonusMainWeaponSkill": 0,
			"fireResist": <?php echo $resistances['resistance']['fire']; ?>,
			"blockRatingPercent": <?php echo $defense['block']['increasePercent']; ?>,
			"natureCrit": <?php echo $spell['crit_rating']['rating']; ?>,
			"hitRatingPercent": <?php echo $melee_stats['hit_rating']['increasedHitPercent']; ?>,
			"sprBase": <?php echo $spirit['base']; ?>,
			"agi_ap": <?php echo $agility['attack']; ?>,
			"dodge": <?php echo $defense['dodge']['percent']; ?>,
			"atkPowerBonus": 0,
			"int_crit": <?php echo $intellect['hitCritPercent']; ?>,
			"rap_petSpellDmg": -1,
			"spr_regen": <?php echo $spirit['manaRegen']; ?>,
			"mastery": 0,
			"expertiseRatingPercent": 0,
			"arcaneResist": <?php echo $resistances['resistance']['arcane']; ?>,
			"sprTotal": <?php echo $spirit['effective']; ?>,
			"manaRegenCombat": <?php echo $spell['mana_regen']['casting']; ?>,
			"rangeCritRatingPercent": <?php echo $melee_stats['crit_rating']['percent']; ?>,
			"resistFrost_pet": -1,
			"dmgRangeSpeed": <?php echo $ranged_stats['damage']['haste']; ?>,
			"dodgeRating": <?php echo $defense['dodge']['rating']; ?>,
			"bonusMainWeaponRating": 0,
			"intBase": <?php echo $intellect['base']; ?>,
			"hasteRatingPercent": <?php echo $melee_stats['haste_rating']['hastePercent']; ?>,
			"frostDamage": <?php echo $spell['power']['value']; ?>,
			"agi_crit": <?php echo $agility['hitCritPercent']; ?>,
			"sta_hp": <?php echo $stamina['health']; ?>,
			"strBase": <?php echo $strength['base']; ?>,
			"armorTotal": <?php echo $defense['armor']['effective']; ?>,
			"critRatingPercent": <?php echo $melee_stats['crit_rating']['percent']; ?>,
			"rangeHasteRatingPercent": <?php echo $melee_stats['haste_rating']['hastePercent']; ?>,
			"rangeBonusWeaponSkill": 0,
			"sta_petSta": <?php echo $stamina['petBonus']; ?>,
			"spellCritRatingPercent": <?php echo $spell['crit_rating']['value']; ?>,
			"dmgRangeMin": <?php echo $ranged_stats['damage']['min']; ?>,
			"rangeHasteRating": <?php echo $melee_stats['haste_rating']['value']; ?>,
			"armorBase": <?php echo $defense['armor']['base']; ?>,
			"critRating": <?php echo $melee_stats['crit_rating']['value']; ?>,
			"spellCritPercent": <?php echo $spell['crit_rating']['value']; ?>,
			"armorPenetration": 0,
			"dmgOffSpeed": 0,
			"resistFire_pet": -1,
			"defense": 0,
			"spellPenetration": <?php echo $spell['hit_rating']['penetration']; ?>,
			"strTotal": <?php echo $strength['effective']; ?>,
			"parryRatingPercent": <?php echo $defense['parry']['increasePercent']; ?>,
			"staTotal": <?php echo $stamina['effective']; ?>,
			"rap_petAp": -1,
			"fireCrit": <?php echo $spell['crit_rating']['rating']; ?>,
			"natureDamage": <?php echo $spell['power']['value']; ?>,
			"holyDamage": <?php echo $spell['power']['value']; ?>,
            "foo": true
});
		});
	//]]>
	</script>
